theme: jekyll-theme-tactile
title: Welcome to Surhud's studio
author: Surhud Khare
email: surhudk@gmail.com
github_username: surhudkhare
linkedin_username: surhudkhare
Description: Feel free to reach out
